Taceback (most recent call last):
  File "run_models.py", line 536, in <module>
    main()
  File "run_models.py", line 409, in main
    run_models(train_data, train_label, test_data, test_label, train_index, test_index, num_f, cnames, fnames, random_state, temp_num)
  File "run_models.py", line 225, in run_models
    train_data, test_data = scale_feature_select(train_data, train_label, test_data, test_label, num_f, cnames, fnames, random_state)
  File "run_models.py", line 182, in scale_feature_select
    pca_weights.to_csv('machine_learning/results/pca_weights_' + args.modality + '.csv')
  File "/home/jlovering/emu/lib/python3.7/site-packages/pandas/core/generic.py", line 3167, in to_csv
    formatter.save()
  File "/home/jlovering/emu/lib/python3.7/site-packages/pandas/io/formats/csvs.py", line 190, in save
    compression=dict(self.compression_args, method=self.compression),
  File "/home/jlovering/emu/lib/python3.7/site-packages/pandas/io/common.py", line 493, in get_handle
    f = open(path_or_buf, mode, encoding=encoding, errors=errors, newline="")
FileNotFoundError: [Errno 2] No such file or directory: 'machine_learning/results/pca_weights_demographic_gad.csv'
Traceback (most recent call last):
  File "run_models.py", line 536, in <module>
    main()
  File "run_models.py", line 409, in main
    run_models(train_data, train_label, test_data, test_label, train_index, test_index, num_f, cnames, fnames, random_state, temp_num)
  File "run_models.py", line 225, in run_models
    train_data, test_data = scale_feature_select(train_data, train_label, test_data, test_label, num_f, cnames, fnames, random_state)
  File "run_models.py", line 182, in scale_feature_select
    pca_weights.to_csv('machine_learning/results/pca_weights_' + args.modality + '.csv')
  File "/home/jlovering/emu/lib/python3.7/site-packages/pandas/core/generic.py", line 3167, in to_csv
    formatter.save()
  File "/home/jlovering/emu/lib/python3.7/site-packages/pandas/io/formats/csvs.py", line 190, in save
    compression=dict(self.compression_args, method=self.compression),
  File "/home/jlovering/emu/lib/python3.7/site-packages/pandas/io/common.py", line 493, in get_handle
    f = open(path_or_buf, mode, encoding=encoding, errors=errors, newline="")
FileNotFoundError: [Errno 2] No such file or directory: 'machine_learning/results/pca_weights_demographic_phq.csv'
Traceback (most recent call last):
  File "run_models.py", line 536, in <module>
    main()
  File "run_models.py", line 409, in main
    run_models(train_data, train_label, test_data, test_label, train_index, test_index, num_f, cnames, fnames, random_state, temp_num)
  File "run_models.py", line 225, in run_models
    train_data, test_data = scale_feature_select(train_data, train_label, test_data, test_label, num_f, cnames, fnames, random_state)
  File "run_models.py", line 193, in scale_feature_select
    chi = chi.fit(train_data, train_label)
  File "/home/jlovering/emu/lib/python3.7/site-packages/sklearn/feature_selection/_univariate_selection.py", line 352, in fit
    self._check_params(X, y)
  File "/home/jlovering/emu/lib/python3.7/site-packages/sklearn/feature_selection/_univariate_selection.py", line 525, in _check_params
    % (X.shape[1], self.k))
ValueError: k should be >=0, <= n_features = 5; got 6. Use k='all' to return all features.
Traceback (most recent call last):
  File "run_models.py", line 536, in <module>
    main()
  File "run_models.py", line 409, in main
    run_models(train_data, train_label, test_data, test_label, train_index, test_index, num_f, cnames, fnames, random_state, temp_num)
  File "run_models.py", line 225, in run_models
    train_data, test_data = scale_feature_select(train_data, train_label, test_data, test_label, num_f, cnames, fnames, random_state)
  File "run_models.py", line 193, in scale_feature_select
    chi = chi.fit(train_data, train_label)
  File "/home/jlovering/emu/lib/python3.7/site-packages/sklearn/feature_selection/_univariate_selection.py", line 352, in fit
    self._check_params(X, y)
  File "/home/jlovering/emu/lib/python3.7/site-packages/sklearn/feature_selection/_univariate_selection.py", line 525, in _check_params
    % (X.shape[1], self.k))
ValueError: k should be >=0, <= n_features = 5; got 6. Use k='all' to return all features.
Traceback (most recent call last):
  File "run_models.py", line 536, in <module>
    main()
  File "run_models.py", line 430, in main
    with open('machine_learning/results/features_' + args.modality + '_' + args.feature_selection + '.json', 'w') as jf:
FileNotFoundError: [Errno 2] No such file or directory: 'machine_learning/results/features_demographic_gad_etc.json'
Traceback (most recent call last):
  File "run_models.py", line 536, in <module>
    main()
  File "run_models.py", line 430, in main
    with open('machine_learning/results/features_' + args.modality + '_' + args.feature_selection + '.json', 'w') as jf:
FileNotFoundError: [Errno 2] No such file or directory: 'machine_learning/results/features_demographic_phq_etc.json'
